### ISSUE TITLE
NSIDC Lidar at Farmer's Loop/Creamer's Field, Alaska

### ISSUE THREAD

**Issue by agentrrb** [SnowEx/snowex_db#27]
Hi there,

I'd like to see about adding two lidar datasets to the snowex database from the NSIDC. Here's the link to the lidar:
https://nsidc.org/data/snex23_lidar/versions/1

The two datasets that are needed are the FLCF lidar canopy heights (SNEX23_Lidar_FLCF_CH_0.25M_20221024_V01.0.tif) and the FLCF lidar snow depths (SNEX23_Lidar_FLCF_SD_0.25M_20230311_V01.0.tif)

**Comment by micahjohnson150** [comment]
@agentrrb take a look at PR #28 . Please take a look at the two scripts added. Each has meta data that I need confirmation on. I have probably most of the info from the lidar but I am guessing on the GPR.
